### ISSUE TITLE
Docs: Feedback for Start a Local Cluster from Binary

### ISSUE THREAD

**Issue by avtarraikmo** [hazelcast/hz-docs#1029]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/get-started-binary.adoc)

Install Enterprise - links to Install Open Source.

Can we update the link?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/f77c058c163bd3001eedc9d11db43c811dfd1198. Also fixed in other 5.x branches.
