### ISSUE TITLE
Docs: Feedback for Enabling Lite Members

### ISSUE THREAD

**Issue by wyohm** [hazelcast/hz-docs#1051]
Hi, I have some feedback about [the lite members page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/maintain-cluster/pages/lite-members.adoc)

The note at the bottom of the page says:

> A data member cannot be downgraded to a lite member back.

Since it followed the section promoting a lite member to a data member, maybe it was supposed to say:

> A data member cannot be downgraded back to a lite member.

But because it applies to all data members (not just ones which were promoted from lite members, I'm assuming) I think it would be better to simply say:

> A data member cannot be downgraded to a lite member.

**Comment by Serdaro** [comment]
Thank you @wyohm, fixed with the above commit.
Also, fyi, the downgrade/demotion feature has been added starting with 5.4: https://docs.hazelcast.com/hazelcast/5.4-snapshot/maintain-cluster/lite-members#demoting-data-members-to-lite-members
