### ISSUE TITLE
Docs: Feedback for Overview

### ISSUE THREAD

**Issue by knurl** [hazelcast/hz-docs#1061]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/HEAD/docs/modules/tiered-storage/pages/overview.adoc)

@oliverhowell Do we need to mention HybridLog to customers? This seems like an implementation detail that is irrelevant to customers.

**Comment by Serdaro** [comment]
hello @knurl , there is a PR (https://github.com/hazelcast/hz-docs/pull/1047) to enhance the Tiered Storage (TS) documentation, in which we mention HybridLog in various sections (capacity planning, configuration, performance and troubleshooting). To make the content flow accurate, we should talk about what HybridLog is in a high-level way in the Overview section.

**Comment by amandalindsay** [comment]
Closing based on Serdaro's comment above and the need for HybridLog to be mentioned
