### ISSUE TITLE
Docs: Feedback for 5.4.0-BETA-2 Release Notes

### ISSUE THREAD

**Issue by wrmay** [hazelcast/hz-docs#1066]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.4-BETA-2/docs/modules/release-notes/pages/5-4-0-beta-2.adoc)

Should we be mentioning TPC here ?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/125203a34832dcaa6774238aa39723d41b3eece7
