### ISSUE TITLE
Docs: Feedback for Cluster Utilities

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#107]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/management/pages/cluster-utilities.adoc)

I think this chapter contains content a bit out of place. To me, "Managing Cluster and Member states", "Defining Member Attributes", "Getting Member Events and Member Sets" and "Enabling Lite Members" has nothing to do with "Cluster Utilities". I agree it might be subjective and maybe needs proper thinking but I guarantee that nobody will find e.g. lite members in the structure under "Cluster utilities" without a search.

**Comment by Serdaro** [comment]
@Holmistr , thanks a lot. To be honest, they were the last minute additions to the document, since somehow they were missed until now by me. It will be properized!

**Comment by Serdaro** [comment]
Fixed with the above commits
