### ISSUE TITLE
Docs: Feedback for INSERT INTO/SINK INTO

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#11]
Hi, I have some feedback about [this page](https://hardcore-allen-f5257d.netlify.app/hazelcast/5.0-snapshot/sql/sink-into.html#examples)

In the examples section, it only shows the very basic case where you're inserting a simple key-value. I would appreciate an example of when you're inserting an object as well, possibly separating those two examples even though they overlap a bit.

I had a simple example like:
* `CREATE MAPPING persons (__key BIGINT, name VARCHAR, age INT) TYPE IMap OPTIONS ('keyFormat'='bigint','valueFormat'='java','valueJavaClass' = 'sql.Person')`
* `INSERT INTO persons (__key, name, age) VALUES (1 , 'Jake', 29);

Additionally, regarding the basic example of adding a key-value entry, I would like a more detailed explanation that the provided example will create an IMap with String as keys and Int values (i.e. IMap<String, Integer>) and that the key (= `__key`) is aliased as `name` and value (`this`) is aliased as `age`.  Also, there's explanation of the `EXTERNAL NAME`. I know it's hidden under the CREATE MAPPING link but it's still not really transparent.

**Comment by JakeSCahill** [comment]
Fixed in this PR: It includes lots of little fixes since the merge to the new repo: https://github.com/hazelcast/hz-docs/pull/7
