### ISSUE TITLE
Right hand side navigation is missing sometimes

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hz-docs#1159]
Due to "#hide-nav" postfix added automatically by Algolia (I think), right hand side navigation is missing sometimes.

To reproduce 

1. go to https://docs.hazelcast.com/home/
2. search for Replicated Map 
3. click on the top page in Platform category
![image](https://github.com/hazelcast/hz-docs/assets/32355782/4820faf7-ebcb-4be3-8c66-58fb7c95ea77)
4. you should go to https://docs.hazelcast.com/hazelcast/5.4/data-structures/replicated-map#hide-nav
5. notice that the navigation is missing on the right
![image](https://github.com/hazelcast/hz-docs/assets/32355782/e0dfbfc5-7cd8-4f20-9933-7873d9a11b90)

**Note**

The issue seems to be happening on 5.4 and not on 5.3.
- https://docs.hazelcast.com/hazelcast/5.3/clients/java#hide-nav navigation is not hidden
- for https://docs.hazelcast.com/hazelcast/5.4/clients/java#hide-nav it's hidden

**Comment by amandalindsay** [comment]
Neither myself or Mykola could replicate this issue so it appears to no longer be a bug.
