### ISSUE TITLE
Docs: Feedback for Production Checklist

### ISSUE THREAD

**Issue by 7erry** [hazelcast/hz-docs#1234]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/ROOT/pages/production-checklist.adoc)

We are recommending CMS for java 8 and it should be G1GC. While G1GC is not the default and it was introduced later in the lifecycle of java 8 it is absolutely the recommendation: https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/g1_gc_tuning.html

**Comment by amandalindsay** [comment]
This issue appears to have been fixed, assuming this is the line in question: '* G1GC is the default recommended GC policy'. 
TBC
