### ISSUE TITLE
Docs: Feedback for REST API

### ISSUE THREAD

**Issue by jgardiner68** [hazelcast/hz-docs#1259]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc)

Images are broken

**Comment by amandalindsay** [comment]
Issue appears to have been fixed in the latest version and the 6.0 snapshot: https://docs.hazelcast.com/hazelcast/latest/maintain-cluster/enterprise-rest-api
