### ISSUE TITLE
Docs: Feedback for Data Affinity

### ISSUE THREAD

**Issue by jimoconnell** [hazelcast/hz-docs#1277]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/cluster-performance/pages/data-affinity.adoc)

The first paragraph has an incomplete sentence:
> "_Data affinity ensures that related entries exist on the same member. If related data is on the same member, operations can_"

Nothing follows the final "can".  The document continues:
> You can achieve data affinity by implementing the [PartitionAware](https://docs.hazelcast.com/hazelcast/5.5/cluster-performance/data-affinity#partitionaware) interface or applying the [partitioning strategies](https://docs.hazelcast.com/hazelcast/5.5/cluster-performance/data-affinity#partitioningstrategy) as described in the following topics.

**Comment by amandalindsay** [comment]
Fixed and issue will be closed when PR merged
