### ISSUE TITLE
Docs: Feedback for Monitoring - SlowOperationDetector

### ISSUE THREAD

**Issue by jgardiner68** [hazelcast/hz-docs#1278]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/maintain-cluster/pages/monitoring.adoc)

The link to SlowOperationDetector goes to the best practices section rather than to https://docs.hazelcast.com/hazelcast/5.5/cluster-performance/threading#slowoperationdetector

**Comment by amandalindsay** [comment]
Fixed and issue will be closed when PR merged
