### ISSUE TITLE
Docs: Feedback for REST API

### ISSUE THREAD

**Issue by wyohm** [hazelcast/hz-docs#1286]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc)

Page cautions about Community Edition REST API being deprecated and suggests seeing the Enterprise REST API page for more information about the replacement. But that's the page the warning is already on, so the link goes nowhere.

Also, the [community edition REST API page](For more info, see [Enterprise REST API](https://docs.hazelcast.com/hazelcast/5.5/maintain-cluster/enterprise-rest-api) can be found via search, but appears to be orphaned (not available via the navigation hierarchy).

**Comment by amandalindsay** [comment]
Fixed by replacing the partial (containing the link) with text
