### ISSUE TITLE
Docs: Feedback for Start a Local Cluster from Binary

### ISSUE THREAD

**Issue by mohinimhetre** [hazelcast/hz-docs#131]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/get-started-binary.adoc)

I am trying to start hazelcast cluster on my local machine. I have downloaded hazelcast-5.0-BETA-1.zip and I am using open jdk for java. I have set javahome and java bin path in Path environment variable. when I run hz-start.bat it stuck at "Starting Hazelcast".

I tried with hazelcast-4.2.2 version, it working fine for it.

**Comment by JakeSCahill** [comment]
@mohinimhetre We've since released 5.0-BETA-2, could you check if this script is still not working for you in the latest version?

**Comment by JakeSCahill** [comment]
Closing this as I think it's related to an old beta version
