### ISSUE TITLE
Docs: Feedback for Client Security

### ISSUE THREAD

**Issue by milkmanbilly** [hazelcast/hz-docs#1314]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/blob/main/docs/modules/security/pages/native-client-security.adoc)
I found 2 mistakes on it when using yaml configuration:
- `ringbuffer` must be `ring-buffer`
- `scheduled-executor-service` must be `scheduled-executor`

With the configuration indicated in the documentation the following errors appear in the logs:
`ringbuffer is not a valid enum value`
`scheduled-executor-service is not a valid enum value`

**Comment by amandalindsay** [comment]
Thank you. The link to the page in question is broken above so the content may have moved. 
To confirm, is this the correct page: 
https://docs.hazelcast.com/hazelcast/5.5/security/client-authorization

**Comment by Rob-Hazelcast** [comment]
Thank you for raising this and apologies for the inconvenience. This appears to have been a mix up between the field names for configuring the feature itself and the field names in the permissions section. I'm going to review all the configuration in this part of the documentation (which is now https://docs.hazelcast.com/hazelcast/5.5/security/client-authorization, as noted above).

Thanks,
Rob
