### ISSUE TITLE
Docs: Feedback for CDC Connector

### ISSUE THREAD

**Issue by pmcgleenon** [hazelcast/hz-docs#1345]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/integrate/pages/cdc-connectors.adoc)

Both of these pages describe using the User Code Deployment feature, which is deprecated

https://docs.hazelcast.com/hazelcast/5.5/integrate/cdc-connectors
https://docs.hazelcast.com/hazelcast/5.5/pipelines/cdc-join#7-start-hazelcast-jet

They should be migrated to use UCN

**Comment by amandalindsay** [comment]
Hi @pmcgleenon Patrick,

Regarding this issue, I understand this topic included cross-refs to 2 topics which refer to the deprecated feature, User Code Deployment. 

To fix this issue, is it simply a case of updating the notes/cross-refs in the 'Notes' as follows:

**1st note:**
NOTE: This page refers to Hazelcast's {enterprise-product-name} CDC connectors. For more information on {open-source-product-name} CDC connectors, see xref:integrate:legacy-cdc-connectors.adoc[].

Question – should this be changed to xref the non-legacy CDC topic?

NOTE: This page refers to Hazelcast's {enterprise-product-name} CDC connectors. For more information on {open-source-product-name} CDC connectors, see xref:integrate: cdc-connectors.adoc[].

**2nd note:** 
If user code has to be used, then the problem can be solved with the help of the User Code Deployment feature. Example configs for that can be seen in our xref:pipelines:cdc-join.adoc#7-start-hazelcast-jet[CDC Join tutorial].

Question – should this be changed to:

If user code must be used, you can use the User Code Namespaces feature. For more information, see xref:clusters:user-code-namespaces.adoc[User Code Namespaces].

Or does it need more than this?

**Comment by pmcgleenon** [comment]
Hi @amandalindsay 

On your first note, I think it makes sense to reference the non-legacy topic

Reading some of the other docs, it looks like Jet doesn't support UCN yet so User Code Deployment must be used.
Maybe adding a [note like this](https://github.com/hazelcast/hz-docs/blob/main/docs/modules/integrate/pages/legacy-cdc-connectors.adoc?plain=1#L98) would be helpful

> Although User Code Deployment has been deprecated, the replacement User Code Namespaces feature does not yet support Jet jobs or pipelines. For now, continue to use the User Code Deployment solution in this scenario. 

@TomaszGaweda  what do you think?

**Comment by TomaszGaweda** [comment]
> 1st note:
NOTE: This page refers to Hazelcast's {enterprise-product-name} CDC connectors. For more information on {open-source-product-name} CDC connectors, see xref:integrate:legacy-cdc-connectors.adoc[].

>Question – should this be changed to xref the non-legacy CDC topic?

No, OSS connector is the legacy CDC connector, so xref to legacy connector is correct here.

> Maybe adding a [note like this](https://github.com/hazelcast/hz-docs/blob/main/docs/modules/integrate/pages/legacy-cdc-connectors.adoc?plain=1#L98) would be helpful

That's a good idea. IIRC There was some job on UCN with Jet, but it was not yet released, so for now the note is the best way to tell users that "hey, we know it should be different, but cannot be _yet_"

**Comment by amandalindsay** [comment]
Thank you @TomaszGaweda and @pmcgleenon for your prompt replies. I have added the note as suggested and will close the issue
