### ISSUE TITLE
Docs: Feedback for SELECT

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hz-docs#135]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/sql/pages/select.adoc)

The TIP section does not display Code Examples link correctly

![Screenshot from 2021-08-26 16-28-25](https://user-images.githubusercontent.com/29387993/130971351-be26bf6f-2a0d-4921-b88e-15f1485daa2f.png)

**Comment by JakeSCahill** [comment]
Fixed in #88
