### ISSUE TITLE
Docs: Feedback for Client Security - Scheduled Executor configuration missing for XML and / or associated Schema

### ISSUE THREAD

**Issue by marcellaxis** [hazelcast/hz-docs#1376]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0/docs/modules/security/pages/native-client-security.adoc)

(The previous is autogenerated, I will leave it in case it is of use to you, but the documentation page where I found the issues is actually [this one](https://docs.hazelcast.com/hazelcast/5.4/security/native-client-security) which stands for version 5.4 Of the Hazelcast Platform documentation - Native Client Security.

In particular, among all the examples, there is one for [Setting permissions for Scheduled Executor Services](https://docs.hazelcast.com/hazelcast/5.4/security/native-client-security). Now, it would seem the XML provided in this example is actually invalid according to the associated XML Schema (I checked myself that there is indeed no "xs:element" declared for it).

There is also no example of this included in the usual "hazelcast-full-example.xml" as far as I can see.

Given the previous, I'm unsure whether this example is actually invalid and these permissions are embedded inside other executor-type's permissions, or rather and most likely, there has been some mistake and the Scheduled Executor Permissions might have not been taken into account either in the examples or worse, they were planned but never implemented.

Also I'm too lazy to do so myself, but I venture the same issue might be present in previous / posterior versions, and in the programmatic / .yml equivalent configurations.

Apologies in advance if I misunderstood something, but otherwise please advise on the correct configuration to be applied.

Cheers!
    Marcell.

**Comment by Rob-Hazelcast** [comment]
Hi Marcell,

Thank you for raising this, and apologies for the delay in getting back to you. The correct XML element name is <scheduled-executor-service> (not <scheduled-executor-service-permission>). You can see this in the full example XML: https://github.com/hazelcast/hazelcast/blob/3175d2c38b47a3de824c0072c1769a6fba22ff78/hazelcast/src/main/resources/hazelcast-full-example.xml#L936.

I'll update the docs for affected versions. The YAML equivalent is correct.

Note that this page has moved in the latest version: https://docs.hazelcast.com/hazelcast/5.5/security/client-authorization#scheduled-executor-service-permission.

Thanks,
Rob

**Comment by Rob-Hazelcast** [comment]
Hi Marcell,

Thank you for raising this, and apologies for the delay in getting back to you. The correct XML element name is `<scheduled-executor-permission>` (not `<scheduled-executor-service-permission>`). You can see this in the full example XML: https://github.com/hazelcast/hazelcast/blob/e6ef7a8a874e445754bf6b9ab04056d812d993da/hazelcast/src/main/resources/hazelcast-full-example.xml#L2650.

I'll update the docs for affected versions. The YAML equivalent is correct.

Note that this page has moved in the latest version: https://docs.hazelcast.com/hazelcast/5.5/security/client-authorization#scheduled-executor-service-permission.

Thanks,
Rob
