### ISSUE TITLE
Docs: Feedback for SQL

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hz-docs#138]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/query/pages/sql-overview.adoc)

We say that

```
For example, this query creates a mapping to a new map called MyMap, which stores the JSON values ticker and amount:
```

But for the query right below it, the map is called `my_map`

```
CREATE MAPPING my_map(
...
```

**Comment by JakeSCahill** [comment]
Fixed in #88
