### ISSUE TITLE
Docs: Feedback for Map

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hz-docs#14]
some of the images seem rather low-resolution

![image](https://user-images.githubusercontent.com/510278/124900419-5284c280-dfe1-11eb-8a7c-d7b84aa3674d.png)

there's also extra indentation on some of the code samples

![image](https://user-images.githubusercontent.com/510278/124900457-5dd7ee00-dfe1-11eb-8312-55b44e6a5b9d.png)

https://hardcore-allen-f5257d.netlify.app/hazelcast/5.0-snapshot/data-structures/map.html

**Comment by Serdaro** [comment]
Fixed with the above commit.
