### ISSUE TITLE
Docs: Feedback for REST API

### ISSUE THREAD

**Issue by pmcgleenon** [hazelcast/hz-docs#1402]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc)

> Hazelcast provides a REST API that allows you to access your data structures and cluster using HTTP/HTTPS protocols.

The REST API allows you to manage the **configuration** for data structures and configure and manage the cluster.
To avoid any confusion, it's worth pointing out that the REST API is a control-plane API for the cluster which is useful for configuration and operational purposes.     It does not provide direct access to any data stored in distributed data structures.

**Comment by amandalindsay** [comment]
PR done to add note based on the above https://github.com/hazelcast/hz-docs/pull/1411
