### ISSUE TITLE
Docs: Feedback for Upgrading to Hazelcast 5.0

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hz-docs#141]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/migrate/pages/upgrade.adoc)

Here I listed my feedbacks about this page.

`Hazelcast 5.0 is fully compatible with former Hazelcast IMDG 4.x and 3.12.x versions.`

- What do we mean here? As far as I know, 3.12.x/4.x and 5.x members are not able to form a cluster. Do we mean we support migrations?

---

`All the 4.x.y and 3.12.x versions of Hazelcast Java client are compatible with Hazelcast 5.0.`

-> Java client 3.12.x cannot work with Hazelcast 5.0, as the client protocols used in those versions are incompatible. The client protocol is redesigned in 4.0.

---

`Classes in impl packages do not provide any compatibility guarantees between versions and are not meant for public use.`

-> Maybe we can also mention `internal` packages. As far as I know, we don't guarantee compatibility for those as well. It would be good to verify this with the core team.

---

`While upgrading to Hazelcast 5.0, if a YAML configuration violates any of the above, the cluster will not start. You need to either edit and update your YAML configuration files accordingly or disable the validation by setting the yaml.config.validation.skip property to true.`

-> I cannot find the `yaml.config.validation.skip` property. We have some other property that enables us to skip validation, maybe we meant this:

`hazelcast.config.schema.validation.enabled`

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/139/commits/fae7a0cba31e344d1c299cf7b5accc4a582c82bd
