### ISSUE TITLE
Docs: Feedback for Installing Hazelcast Community Edition

### ISSUE THREAD

**Issue by myawn** [hazelcast/hz-docs#1415]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/install-hazelcast.adoc)

The download instructions for using a package manager suggests using a version tag of 5.5.2, but patch releases aren't available for community edition so this should be 5.5.0 instead.

**Comment by Rob-Hazelcast** [comment]
Thanks for raising this. We've updated the version number variables so this won't be an issue in future.
