### ISSUE TITLE
Docs: Feedback for Migrating Between IMDG 3.x/4.x and Platform 5.0 Releases

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hz-docs#142]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/migrate/pages/migration-tool-imdg.adoc)

`You can then gradually transfer applications from the 3.x clients to applications using 4.x clients. After all applications are using the 4.x clients and reading/writing data from/to the 5.0 members, the 3.12 cluster and the 3.x clients can be shut down.`

-> There is nothing wrong with this statement, as 4.x clients are able to communicate with 5.x clusters. But on the diagram above, we are displaying something that uses 5.0 client but here we are mentioning about 4.x clients. Maybe we could change that.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/139/commits/fae7a0cba31e344d1c299cf7b5accc4a582c82bd
