### ISSUE TITLE
Docs: Feedback for Get Started with SQL Queries

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#143]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/query/pages/get-started-sql.adoc)

Why are we using `SINK INTO` for the SQL example of adding data to a map?  This will be confusing to the majority of SQL users, maybe only streaming users will understand this.

I guess this was done before we had INSERT functionality.

Anyway, can we please change this before the 5.0 release?

**Comment by JakeSCahill** [comment]
Fixed, but can't find the PR. You can see the change here: https://github.com/hazelcast/hz-docs/blob/main/docs/modules/sql/pages/get-started-sql.adoc
