### ISSUE TITLE
Docs: Feedback for Hazelcast Overview

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#144]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/ROOT/pages/index.adoc)

Clicking `NEXT` at the bottom of this page takes me out of the standard docs and into Hazelcast Cloud docs.  From then on if I follow the NEXT buttons I never return to the standard docs.

Not sure how we fix this, but I found it confusing to be suddenly thrown out of the main docs and the left menus change, etc.

It can be hard to spot initially as the doc layouts/colours are exactly the same.

**Comment by JakeSCahill** [comment]
Hmm, the cloud docs link is new to try and promote Cloud as a starting point.

We have two options to fix this:

- Remove the link to the Cloud tutorial.
- Remove the Next/Previous links for the overview page (we could provide a 'Next Steps' section with a list of pages).
