### ISSUE TITLE
Docs: Feedback for Start a Local Cluster in Docker

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#145]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/getting-started/pages/get-started-docker.adoc)

We keep showing the setting of PUBLIC IP to start all the docker members.

Can we put some explanation into why this is required, we know it's to allow smart client connectivity, so maybe some information or a link into how that works with the multiple sockets, etc.

So in our examples to add data for the SQL one it's not required but for the Language APIs it is.

We should also point out that if the clients(application) and the servers all sit in docker there's no need to include this public IP setting.

**Comment by JakeSCahill** [comment]
Fixed in #181
