### ISSUE TITLE
Docs: Feedback for Configuring How Clusters Handle Single-Member Failures

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#152]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/storage/pages/recover-single-member.adoc)

This warning makes no sense and there's also a grammar issue and typo for `propery`....

`Do not use configure this propery if your cluster also stores in-memory data. A non-zero value will stop the cluster from migrating in-memory data. As a result any data that is not persisted will be lost if the member restarts, including backups.`

It says if you set a non-zero value it will stop the cluster from migrating in-memory data.

This is not true.

It will stop migrating data up to the rebalance timeout specified by the property, after that it will rebalance.

This warning is trying to convey that within that period if you lose the primary AND the backup member you have lost data.

But is that true?  Isn't data persisted to disk.  

Can you please check with the storage team on this.

**Comment by JakeSCahill** [comment]
I checked with the storage team and although we should (and will) improve the warning, it is still valid.

> It will stop migrating data up to the rebalance timeout specified by the property, after that it will rebalance.

Migrations don't happen automatically after the rebalance delay. It depends on whether the member rejoins within the delay or after it.

If a member rejoins within the rebalance delay, then all its persisted data will be restored from disk and **no migrations will take place**. Any in-memory data in member B's partitions will be lost, and member B will still be listed as the owner of those partitions. So even if the cluster has backups of in-memory data in maps, requests will go to member B (unless the members have backup reads enabled).
