### ISSUE TITLE
Docs: Feedback for Start a Local Cluster in Docker

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#153]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/getting-started/pages/get-started-docker.adoc)

The Docker script for starting the SQL shell is incorrect. It should be:

docker run \           
--network hazelcast-network \
-it \
-rm hazelcast/hazelcast:$HAZELCAST_VERSION \
bin/hz-cli sql --targets dev@$LOCAL_IP

**Comment by JakeSCahill** [comment]
Fixed in #181
