### ISSUE TITLE
Docs: Feedback for Start a Local Cluster in Docker

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#154]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/getting-started/pages/get-started-docker.adoc)

inconsistency in code samples. SQL uses myDistributedMap. Others use my-distributed-map

**Comment by JakeSCahill** [comment]
We tend to use `_` in SQL, so we changed the tutorial to use this to be consistent with other SQL examples. #181
