### ISSUE TITLE
Docs: Feedback for Queue

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hz-docs#165]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/data-structures/pages/queue.adoc)

Similar to https://docs.hazelcast.com/imdg/latest/getting-started.html#your-first-client-application,
we should have corresponding code samples for other clients, too.

All client repos have their own code samples for Queue.

Thanks!

**Comment by Serdaro** [comment]
Closed with https://github.com/hazelcast/hz-docs/pull/329
