### ISSUE TITLE
Docs: Feedback for Backing Up Persisted Data

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#171]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/storage/pages/backing-up-persistence.adoc)

This section still mentions `HotRestartService`. I guess this will (or was) renamed to remove the HotRestart name. CC @vbekiaris . We need to check other places in the documentation for that as well.

**Comment by JakeSCahill** [comment]
It's on our radar. The PR is still open to actually update this in the codebase: https://github.com/hazelcast/hazelcast/pull/19404

**Comment by JakeSCahill** [comment]
Fixed in #186
