### ISSUE TITLE
Docs: Feedback for Get Started with Stream Processing (Embedded)

### ISSUE THREAD

**Issue by ryan-st** [hazelcast/hz-docs#173]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/pipelines/pages/stream-processing-embedded.adoc)

        Config config = new Config();
        JetConfig jetConfig = config.getJetConfig();

the config object does not have the method `getJetConfig()`. Is this outdated?

**Comment by JakeSCahill** [comment]
These docs are for version 5.0. The `getJetConfig()` method is part of the `Config` API in this version: https://docs.hazelcast.org/docs/5.0-SNAPSHOT/javadoc/com/hazelcast/config/Config.html#getJetConfig--
