### ISSUE TITLE
Jet calculate PI tutorial: inconsistencies in the description (https: //hazelcast.com/blog/jet-calculates-pi-using-python/)

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hz-docs#176]
Jet calculate PI tutorial: inconsistencies in the description (https: //hazelcast.com/blog/jet-calculates-pi-using-python/)
1. Not correct Pi definition, per text it is "**Pi is the ratio of a circle’s radius to its circumference**" but expected to be "a**s the ratio of a circle's circumference to its diameter**"
2. Definition of Monte Carlo Pi calculation inconsistency: In the test it is ". **The proportion of points inside compared to outside multiplied by 4 gives us an approximation to Pi**" but should be "**compared to the total number of points**", see for details  https://www.geeksforgeeks.org/estimating-value-pi-using-monte-carlo/

**Comment by JakeSCahill** [comment]
This issue is about a blog post, not the docs. Marketing should be made aware of this issue.
