### ISSUE TITLE
document ConfigXmlGenerator

### ISSUE THREAD

**Issue by fbarotov** [hazelcast/hz-docs#178]
`ConfigXmlGenerator` is part of the [public API](https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1631601705203800) and it would be great if we document it so users are aware of it. 

Currently, after visiting https://docs.hazelcast.com/hazelcast/latest/getting-started/quickstart.html when I search `ConfigXmlGenerator` on `Search docs` section, nothing pops up.

**Comment by Serdaro** [comment]
Closing in favor [DOCS-666](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-666).
