### ISSUE TITLE
Missing reference for scripts

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hz-docs#183]
We have no reference that lists all scripts that come with Hazelcast and descriptions of what they do. As a developer, when I download Hazelcast, I want to know what these scripts do and how to use them. We are missing a centralized reference like this. For example, we have a page 'Cluster Utilities' that describes the `hz-cluster-admin` (previously `cluster.sh`) script. Ideally, the information such as parameters would be on a reference page for that script. Then the specific uses would appear in the correct place.

I think this relates to the issues described by @Holmistr in #107

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-667](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-667).
