### ISSUE TITLE
Docs: Feedback for Map

### ISSUE THREAD

**Issue by seii** [hazelcast/hz-docs#187]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/data-structures/pages/map.adoc)

The configuration example shown for Maps under the sub-heading `Required Configuration Changes When Using NATIVE` is incorrect, and uses an invalid tag.

Current version:
```
<hazelcast>
    ...
    <map name="nativeMap">
        <in-memory-format>NATIVE</in-memory-format>
        <eviction-percentage>25</eviction-percentage> <--! NO IMPACT with NATIVE -->
    </map>
    ...
</hazelcast>
```

Should be:
```
<hazelcast>
    ...
    <map name="nativeMap">
        <in-memory-format>NATIVE</in-memory-format>
        <eviction eviction-policy="LRU" max-size-policy="USED_NATIVE_MEMORY_PERCENTAGE"  size="20"/>
    </map>
    ...
</hazelcast>
```

**Comment by Serdaro** [comment]
Fixed with the above PR.
