### ISSUE TITLE
Update documentation after merging hazelcast-jet-sql, hazelcast-sql and hazelcast-sql-core

### ISSUE THREAD

**Issue by AyberkSorgun** [hazelcast/hz-docs#19]
Module (and jar) `hazelcast-jet-sql` was merged with `hazelcast-sql` and `hazelcast-sql-core`. Parts of the documentation refer to `hazelcast-jet-sql` jar, should be updated.

Item to migration guide should be added.

**Comment by Serdaro** [comment]
Migration Guide had been updated with this information.
