### ISSUE TITLE
Improve the structure of the getting started tutorials

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hz-docs#198]
Moved from a comment in #197 by @naadhira 

Proposed structure:

- Installing Hazelcast
- Starting a Cluster (includes Mgmt Ctr, adding second cluster member)
- Working with In Memory Storage (pull this from existing Starting a Cluster, add a step with a second client to read data from the cluster)
- Working with Real Time Processing (this tutorial, with the whole "start a cluster" stuff removed and just the commands to submit to an already-running cluster, both local and Docker.)
- 
This structure sets you up for integrating Cloud as well - the last two tutorials should only need minor additions to include connecting the client to a cloud and submitting a job to the cloud (when we get there).

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-669](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-669).
