### ISSUE TITLE
Enrichment use-case not documented

### ISSUE THREAD

**Issue by AyberkSorgun** [hazelcast/hz-docs#20]
I want to enrich streaming data.

This use-case is not documented.

Notably, there is no documentation for JOINs.

**Comment by Serdaro** [comment]
@AyberkSorgun , I think now we have a content for co-grouping and joins, with an example: https://docs.hazelcast.com/hazelcast/5.0-beta-1/pipelines/transforms.html#co-group-join

**Comment by Serdaro** [comment]
Please see https://docs.hazelcast.com/hazelcast/latest/pipelines/map-join.html
