### ISSUE TITLE
Provide documentation for logging in custom code

### ISSUE THREAD

**Issue by AyberkSorgun** [hazelcast/hz-docs#21]
As a developer, I want to log. I want to use the common logging infrastructure so I don't have to change logging levels in multiple places. I want to use a standard API for logging (slf4j preferably).

Provide documentation on 

- how to change logging levels in the platform

- the logging infrastructure in the platform so I can hook into it (what jar's I should depend on, what's in the runtime etc..)

**Comment by Serdaro** [comment]
@AyberkSorgun , could you please check https://docs.hazelcast.com/hazelcast/latest/maintain-cluster/monitoring.html#logging and let us know your feedback?

**Comment by Serdaro** [comment]
The whole logging concept has been improved in file:///Users/serdarozmen/Desktop/hz-docs/test/hazelcast/5.1-SNAPSHOT/maintain-cluster/monitoring.html#logging
