### ISSUE TITLE
Docs: Feedback for Get Started with SQL Over Kafka

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#212]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0/docs/modules/sql/pages/learn-sql.adoc)

Step 2 should start with instructions on opening the SQL shell.

Output from step 5.5 does not match map contents. Output should be: 

+--------------------+--------------------+--------------------+--------------------+
|               __key|ticker              |company             |              amount|
+--------------------+--------------------+--------------------+--------------------+
|                   2|EFGH                |The EFGH            |                  20|
|                   1|ABCD                |The ABCD            |                  10|
+--------------------+--------------------+--------------------+--------------------+

**Comment by JakeSCahill** [comment]
A connection to the SQL shell is listed in the prerequisites.
