### ISSUE TITLE
[Recommendation] When trying to edit latest version create a new branch from main

### ISSUE THREAD

**Issue by ramizdundar** [hazelcast/hz-docs#220]
When trying to edit page, it creates a new branch from 5.0 for example. This could be changed to main branch in my opinion.

**Comment by Serdaro** [comment]
AFAIC, it is better for us to allow the readers to send edit requests/bugs for the version that they are reading. Mostly, it is a research time for the docs team when such requests come; the change request may be valid for that specific version but not for the snapshot, or vice versa.

**Comment by ramizdundar** [comment]
Ok, I understand. I am closing this.
