### ISSUE TITLE
[Recommendation] Some titles are not clear that they are title

### ISSUE THREAD

**Issue by ramizdundar** [hazelcast/hz-docs#221]
For example this is a subtitle but isn't different from a normal text. https://docs.hazelcast.com/hazelcast/5.0/data-structures/managing-map-memory#size-attributes (starts with `====` in the `.adoc` file). Maybe we could change their size or font?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-docs-ui/pull/190
