### ISSUE TITLE
Comments on https://docs.hazelcast.com/hazelcast/5.0/migrate/evaluation-tool.html#copy-data-from-5-x-to-3-x

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hz-docs#225]
There are a couple of places of possible improvement after page review:

1. "**You can also have it using Maven under com.hazelcast with the name "Hazelcast 3 Connector**"." - I think we need 3 different dependencies to use it from maven - 
            <artifactId>hazelcast-3-connector-common</artifactId>
            <artifactId>hazelcast-3-connector-interface</artifactId>
            <artifactId>hazelcast-3-connector-impl</artifactId>
- so it is better to give a link or full example of Maven dependencies since it is required for code samples to work.
2. **"You need to have a client to connect to the remote (3.x) cluster from 5.x. For this, a client configuration should be provided to identify the 3.x cluster..**" This sounds like you need to do something with a client directly. But, in reality, you need just put a configuration. I would propose to refactor to a single sentence like "To configure a connector, you need to provide it with Hz3 client configuration"
3. Steps 1 and 5 of examples are the same for all examples. Isn't it better to move them to a single "configuration" subsection? It should reduce the amount of text.
4. "**Above libraries (JAR files) should exist in the directory specified by the hazelcast.jet.custom.lib.dir property. This is already set up for the distributions of 3.x member/client and connector**." - Could we place here an example of what to do if you are using Maven? It is just 
System.setProperty(ClusterProperty.PROCESSOR_CUSTOM_LIB_DIR.getName(),  libDirPath);
5 "**serialization interfaces, you do not to perform**" I think, "need" is missed.
6. We are referring to this connector as a "tool" mainly, so it is impossible to find it on docs search by "hazelcast 3 connector". It seems it could confuse customer developers. 
7. "**See Sources and Sinks**" - this is a link to "https://docs.hazelcast.com/hazelcast/5.0/integrate/connectors" which is "Connector Guides", isn't it better to reference it by page name? Also, Hz3Source and Hz3Sink are not on the list, is it expected?

**Comment by Serdaro** [comment]
1 - Agreed
2 - Agreed
3 - Actually there are slight differences between copying data sections, and major differences in enrichment section. I'd prefer to keep them as it is, in case I wanna do a specific task using the connector and wanna focus only on that relevant section.
4 - Agreed
5 - Agreed
6 - I tried on 5.0 docs, searching as "hazelcast 3 connector", the first four suggestions in the search results box directed me to this evaluation section.
7 - That link and also the one following it (enrich a stream) aims to educate a user what are sources/sinks and what does it mean to enrich a stream. But, let me check on putting more clarifications on the concepts, in general, i.e., tool, connector, source, sink, etc.
