### ISSUE TITLE
Docs: Feedback for Ingest data into your cluster

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#24]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hazelcast-platform/edit/master/docs/modules/ingest-data/pages/overview.adoc)

I would suggest we just call it "Loader" as MapLoader is not applicable to Queues or Sets, for example, they have different named interfaces.

**Comment by Serdaro** [comment]
The section in question has become https://docs.hazelcast.com/hazelcast/5.0-beta-2/ingest/overview.html
