### ISSUE TITLE
Docs: Feedback for Improving the Performance of SQL Queries

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#241]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0/docs/modules/sql/pages/improving-performance.adoc)

More of a question than a problem: does data affinity really apply with the SQL engine? Since SQL queries use Jet/DAG? It seems like the location of the data wouldn't make much difference to the performance of an SQL query if the job itself is broken up into distributed steps across the cluster.

**Comment by viliam-durina** [comment]
All steps of a job normally run on all members. Data is moved between members only when some operation requires it, e.g. for sorting (moved to one member) or join/aggregation (grouped by the join/aggregation key) etc. Also, the results are passed through one member.

This page might enlighten you: https://jet-start.sh/docs/concepts/dag

**Comment by JakeSCahill** [comment]
@viliam-durina could you confirm the above, please?
