### ISSUE TITLE
Docs: Feedback for Querying Maps with the Predicate API

### ISSUE THREAD

**Issue by sancar** [hazelcast/hz-docs#257]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/query/pages/querying-maps-predicates.adoc)

Can we put a warning to this document about HazelcastJsonValue to make it clear that you can not use it with paging predicate unless you set an explicit comparator ? The fact that HazelcastJsonValue is not comparable may not be obvious to users. See

https://hazelcast.slack.com/archives/C034YQBTG/p1634818818006700

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-670](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-670).
