### ISSUE TITLE
Uplifting MapStore / MapLoader

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hz-docs#271]
Currently, MapStore/MapLoader is located in the documentation as a subsection of the Map data structure, which is not so visible.

_Develop Solutions > Distributed Data Structures > Map > [Working with an External Data Store](https://docs.hazelcast.com/hazelcast/5.0/data-structures/working-with-external-data)_

Since this capability addresses one of the major use cases, I believe we should uplift this section, i.e. add it directly to the _Develop Solutions_ section.

An idea without moving the current section:
We could consider adding a subsection directly under the Develop Solutions named **_“Working with External Databases / Data Stores“_** which has a very short introduction with a link to the actual part that is under the Map section.

**Comment by JakeSCahill** [comment]
This is something that we are planning to address in the new year.

Something that we started before the Platform release was this kind of use case overview where we discuss what features you can use to achieve different use cases: https://docs.hazelcast.com/hazelcast/latest/ingest/overview

> What’s clear is that we are missing an additional layer of docs. We have the core docs, which document the features, what they are for and how to use them. But Hazelcast is a building block, so we need another layer of guides that support Hazelcast for core use cases. The core docs are a reference for those who need deeper understanding. We still technically have guides in the core docs but they are guides for using features.

For each use case overview:

- What is the use case?
- How is Hazelcast a good fit?
- What features do you need to implement?

For each guide:

- Make the title specific such as Creating a Write-Through Cache with MapLoader
- Define who the guide is for
- List any prior knowledge you need to have (link to resources)
- Link a GitHub repository where you can download the source code
- Mention versions of Hazelcast products/external tools that the guide has been tested on

**Comment by burakcelebi** [comment]
Great to hear this, @JakeSCahill! Thank you.
