### ISSUE TITLE
Docs: Feedback for Mapping to Kafka

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#278]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0/docs/modules/sql/pages/mapping-to-kafka.adoc)

This page shows SQL CLI mapping, but not the equivalent function call. See the SQL file mapping for an example of what I think is missing.

**Comment by JakeSCahill** [comment]
@naadhira could you clarify what you mean by 'function call'?

**Comment by naadhira** [comment]
As I said, see SQL file mapping.  

![image](https://user-images.githubusercontent.com/39539528/141872658-fc0dcf30-2532-47bd-9ada-f253be60677e.png)

![image](https://user-images.githubusercontent.com/39539528/141872707-9b67feb6-e8fb-4c10-9143-56f03f950052.png)

Is there an equivalent for Kafka?

**Comment by JakeSCahill** [comment]
We don't have such a function for Kafka. See the reference: https://docs.hazelcast.com/hazelcast/latest/sql/expressions#file-table-functions
