### ISSUE TITLE
Docs: Feedback for Queue and Topic Pages

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hz-docs#28]
Hi, I have some feedback about [this page](https://hardcore-allen-f5257d.netlify.app/hazelcast/5.0-snapshot/data-structures/queue.html)

"Hazelcast distributed queue is an implementation of java.util.concurrent.BlockingQueue. Being distributed, Hazelcast distributed queue enables all cluster members to interact with it. Using Hazelcast distributed queue, you can add an item in one cluster member and remove it from another one."

This one talks only about embedded mode, and no need to mention BlockingQueue as it's not relevant for non-Java users. Same problem exists on the Topic page, so I won't repeat it here.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/128
