### ISSUE TITLE
"Overriding configuration" doesn't describe overriding of named entities

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hz-docs#281]
https://github.com/hazelcast/hz-docs/blob/main/docs/modules/configuration/pages/overriding-configuration-settings.adoc
The page contains configuration examples for entities not referenced by name.
Please consider the example on page https://docs.hazelcast.com/hazelcast/5.0/wan/quick-start:
```
<map name="replicatedMap">
                <wan-replication-ref name="replication"/>
 </map>
```
This config will be converted to env variable:
"HZ_MAP_**REPLICATEDMAP**\_WANREPLICATIONREF\_**REPLICATION**_NAME", "**replication**"
It will be good if these rules will be documented

**Comment by Serdaro** [comment]
Updated https://docs.hazelcast.com/hazelcast/latest/configuration/configuring-with-system-properties#naming-system-properties-and-environment-variables
