### ISSUE TITLE
Docs: Feedback for Get Started with SQL Over Files

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#286]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0/docs/modules/sql/pages/get-started-sql-files.adoc)

See screen cap:  

![image](https://user-images.githubusercontent.com/39539528/141539001-1ad1f673-fe67-4974-985f-7226223cf27a.png)

Mapping does not work with subsequent data entry. The next step is a join that uses the name from the CSV file to match to the key in the in-memory map. This matches the mapping, but not the data entry.

before correcting this, determine what the common/best practice is - to use a unique record identifier (e.g. an integer key value), or to use part of the data itself (e.g. name) as the key in our key/value store. Then change the federated queries and ingestion into IMap accordingly.

**Comment by JakeSCahill** [comment]
It looks like the mapping is just missing the `__key` field.

Keys need to be unique, so using something like `name` in this example wouldn't work. The purpose of this tutorial is just to introduce users to SQL over files. Discussing strategies for storing different data types in a map should be a different topic.

**Comment by naadhira** [comment]
In the Imap tutorial, we use a country name for the key field rather than a unique identifier. My comment about "best practices" was more around "we should demonstrate the right way to do things" rather than adding any discussion about it in the docs. 

I will proceed with this specific demo by adding the __key. But we should have a look at the IMap demo and see if a "proper" key field should be added.
