### ISSUE TITLE
Docs: Feedback for Compact Serialization (BETA)

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#297]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0/docs/modules/serialization/pages/compact-serialization.adoc)

Under "zero configuration", just after the list of field types, the page says:

"For example, assume that we have the same Employee class as above."

There's no Employee class above. I assume this is an artifact of breaking things into smaller pages.

**Comment by srknzl** [comment]
@Serdaro I think this is solved. Can we close ?

**Comment by Serdaro** [comment]
Indeed.. https://github.com/hazelcast/hz-docs/commit/7bbd8e98af74666bd0133b3d87207f7c2fafe31c
