### ISSUE TITLE
Clarify `json` and `json-flat` distinction

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hz-docs#303]
See https://docs.hazelcast.com/hazelcast/5.1-snapshot/sql/mapping-to-maps#json-objects

It mention `json-flat` but doesn't confirm how it differs from JSON (`json`), nor when the latter will be supported.

**Comment by JakeSCahill** [comment]
We added a page to clarify this for the 5.1 beta: https://github.com/hazelcast/hz-docs/pull/330/files#diff-0d6842b32673f08345921865822d25b31052bfba59eddb8963c5445a4a9cabc2
