### ISSUE TITLE
Revert 'Hazelcast IMDG Enterprise Feature' label

### ISSUE THREAD

**Issue by mario45211** [hazelcast/hz-docs#310]
Hi,

I kindly asking for revert 'Hazelcast IMDG Enterprise Feature' label at the begining of any chapter in 5.x documentation, which is paid content, like in version 4.x documentation. I just wasted my time during my system designing, misunderstanding that TLS/SSL feature is available in open-source distribution.

Best regards!

**Comment by JakeSCahill** [comment]
Thanks @mario45211 - we are working on some improvements that will make the distinction clearer between Enterprise content and OS content.

**Comment by JakeSCahill** [comment]
@mario45211 we have a draft pull request here. We welcome your feedback and suggestions 😄 

https://github.com/hazelcast/hazelcast-docs-ui/pull/140
