### ISSUE TITLE
Docs: Feedback for Configuring Jobs

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#324]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/pipelines/pages/configuring-jobs.adoc)
 
 There is no context for the Java configuration options. Where does this go?

**Comment by JakeSCahill** [comment]
This is for embedded mode - we usually use the label `Java member API`. Would this be clearer?

**Comment by Serdaro** [comment]
@naadhira , ☝️

**Comment by amandalindsay** [comment]
I'm no longer seeing a topic called configuring-jobs.adoc, so not sure this is still an issue, or whether this applies only to previous versions?
