### ISSUE TITLE
Docs: Feedback for Configuration

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#333]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/cp-subsystem/pages/configuration.adoc)

When I search for "Configuration" it takes me to this page about CP configuration.

We should try to make that search go to something more general on Hazelcast configuration.

**Comment by JakeSCahill** [comment]
Fixed in https://github.com/hazelcast/hz-docs/pull/344
