### ISSUE TITLE
Docs: Feedback for Tiered Storage

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#335]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/ROOT/pages/tiered-storage.adoc)

I suggest transforming the second paragraph into a "when do you use" list with bullet points - it's more clear and it will catch reader's eye as the question "What is this good for?" is always the first one. Therefore, I propose adjusting it a bit like (maybe even a separate headline "Why use Tiered Storage?" or something like that):
```
* Fewer Hazelcast members for large maps - if you have a map having 1 TB of data, you may be needing around 10 Hazelcast members if all data is kept in the memory; with Tiered Storage, you would need one or two members depending on your cluster’s availability needs.
* Size-comfortable SQL operations - when you do table joins in SQL, the intermediate result may become too large to fit in the memory; with Tiered Storage this is not an issue. 
```

The third paragraph seems like more technical details. From a getting started perspective, you don't want to read right away, you read it after you made your initial stuff working and you're interested in the details. Therefore, I suggest moving this to the end of the page under separate section like "How it works?" or "Technical details".

The fourth paragraph talks about future plans. I would move this after the "Configuring Tiered Storage" section to further enable getting started experience. 

In the code sample, it also shows the fine-tunning properties such as `write-io-thread-count`. AFAIK, they are optional and in most cases, users won't change them. In general, I would like to see the first code samples minimal - list only what's necessary to get the thing up and running. And explain the additional settings in a special chapter. Very much like we do in WAN - quickstart (https://docs.hazelcast.com/hazelcast/latest/wan/quick-start) and talk about fine tuning in separate section (https://docs.hazelcast.com/hazelcast/latest/wan/tuning).

I miss "Not yet supported" (or something like that) section. It's especially important for Tiered Storage as I imagine a lot of users will expect recovery capabilities from a disk based solution. That is not supported in 5.1. It has to be made explicit, probably a separate section.

Lastly, we should make clear in the documentation our intentions about future pricing. Please see the "Enterprise or Open Source" section in the respective ProductBoard item: https://hazelcast.productboard.com/roadmap/3100072-release-timeline-roadmap/features/8945089/detail
Please, include the info about plan in 5.2 in the Docs.

**Minor:**
* `additional guarantees including lesser Hazelcast members` - shouldn't it be `fewer`? I really don't know, just asking.
* `The in-memory format for the map having Tiered Storage enabled should be NATIVE. ` - I believe we it **must** be `NATIVE`, right? `Should` always confuses me like I have an option but I remember that there's some technical writer guideline whether to use `should` or `must`. Just a thought.

**Comment by Serdaro** [comment]
Type in the commit text.. Fox -> Fix

**Comment by Serdaro** [comment]
Here is the improved content: https://github.com/hazelcast/hz-docs/blob/5.1-BETA-1/docs/modules/ROOT/pages/tiered-storage.adoc

**Comment by Holmistr** [comment]
Thank you @Serdaro ! Looks great! Feel free to close this issue once you merge it to the upstream Beta docs.

**Comment by Serdaro** [comment]
Closing with https://github.com/hazelcast/hz-docs/pull/338
