### ISSUE TITLE
Docs: Feedback for Tiered Storage

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hz-docs#341]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/ROOT/pages/tiered-storage.adoc)

If you try to start a hazelcast member with just the following configuration the member will fail to start as Native Memory has not been enabled.

I went to the HD Memory Page and copied the example XML, I guess we should include this in this doc and also maybe give a link to HD Memory page?

[https://docs.hazelcast.com/hazelcast/5.1-snapshot/storage/high-density-memory](url)

```
<native-memory allocator-type="POOLED" enabled="true">
        <size unit="MEGABYTES" value="512"/>
        <min-block-size>16</min-block-size>
        <page-size>4194304</page-size>
        <metadata-space-percentage>12.5</metadata-space-percentage>
        <persistent-memory>
            <directories>
                <directory numa-node="0">/mnt/pmem0</directory>
                <directory numa-node="1">/mnt/pmem1</directory>
            </directories>
        </persistent-memory>
</native-memory>
```

**Comment by Serdaro** [comment]
Closing with https://github.com/hazelcast/hz-docs/pull/338
