### ISSUE TITLE
Docs: Feedback for Distributed Data Structures

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hz-docs#36]
Hi, I have some feedback about [this page](https://hardcore-allen-f5257d.netlify.app/hazelcast/5.0-snapshot/data-structures/distributed-data-structures.html)

We can change the ordering based on the usage patterns of data structures. For example, Replicated Map is mentioned way down but it's the 3rd popular data structure where as things like Cache and Set etc are pretty niche.

Here's data for 4.2:
![image](https://user-images.githubusercontent.com/510278/125413480-d9e9ee2e-f282-4fe2-9729-5239222cfe10.png)

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/128
