### ISSUE TITLE
Update Logging Configuration section with new customization methods

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hz-docs#366]
As per https://github.com/hazelcast/hazelcast/pull/20528 :

- Provide ability to customize the default pattern via LOGGING_PATTERN
env variable. To support patterns with exception inside the pattern the
default config file now sets alwaysWriteExceptions=false and `%eXe` was
added to the default pattern configuration.

- Provide ability to specify the configuration file via LOGGING_CONFIG
env variable. This takes either relative or absolute path, or file in
config directory. If not set config/log4j2.properties is used.

- Add support for JsonTemplateLayout (log4j-layout-template-json
dependency) and a built in configuration file using JsonLayout.json as
default for the template.

- The json template can be customized via LOGGING_JSON_TEMPLATE, see
https://logging.apache.org/log4j/2.x/manual/json-template-layout.html#event-templates
for out of the box available templates.

- Small cleanup related to default LOGGING_LEVEL - moved the default out
of the startup scripts

Example use:
- Use different pattern:
`LOGGING_PATTERN='{"time":"%date{ISO8601}", "logger": "%logger{36}", "level": "%level",  "msg": "%enc{%m %xEx}{JSON}"}%n' bin/hz start`

- Use different config file:
`LOG4J2_CONFIG=log4j2-json.properties bin/hz start`

- Use json config file with another template:
`LOG4J2_CONFIG=log4j2-json.properties LOGGING_TEMPLATE="classpath:EcsLayout.json" bin/hz start`

Similarly with docker via `-e ....`

**Comment by frant-hartm** [comment]
There was a typo in the PR, LOG4J2_CONFIG should be LOGGING_CONFIG.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/375
