### ISSUE TITLE
Docs: Feedback for Hazelcast Cloud "Next Page" link tag is wrong

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hz-docs#394]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/deploy/pages/deploying-hazelcast-cloud.adoc)

on this page (and I think on some other pages as well) the next page link at the bottom says "overview" but it actually goes to "Public Clouds" page, for this specific example.

**Comment by Serdaro** [comment]
The whole previously known "Deploy and Manage Clusters" chapter has been restructured into "Deploy Clusters" and "Configure and Manage Clusters" chapters, eliminating the "next page" issues.
