### ISSUE TITLE
Hazelcast Spring should mention how it should be used with Spring Boot

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hz-docs#402]
When `hazelcast-spring` is used with Spring Boot there is an issue with different versions, 
See slack discussion https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1646918316665169

The following chapter 
https://docs.hazelcast.com/hazelcast/5.1/integrated-clustering/spring

should contain a section _Using with Spring Boot_ containing info that the user needs to set the `hazelcast.version` maven property to 5.1 or add a dependency on `hazelcast` with the correct version.

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-671](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-671).
