### ISSUE TITLE
Gradle cannot detect Automatic-Module-Name in Hazelcast 5+

### ISSUE THREAD

**Issue by nkayisavera** [hazelcast/hz-docs#403]
Hi, about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/deploy/pages/running-in-modular-java.adoc),

Gradle cannot detect the automatic-module-name in Hazelcast-5.1.jar because /META-INF is not the first or second entry in the jar file.
The same issue has been reported to Gradle regarding [other libraries](https://github.com/gradle/gradle/issues/15270).

**Comment by ldziedziul** [comment]
Issue copied to the main repo: https://github.com/hazelcast/hazelcast/issues/20968

**Comment by ldziedziul** [comment]
@nkayisavera many thanks for the report, the issue will be fixed in the `5.1.2` release
