### ISSUE TITLE
Docs: Feedback for Client Security

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#409]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/security/pages/native-client-security.adoc)

The tile of https://docs.hazelcast.com/hazelcast/5.1/security/native-client-security#management-center-permission is "Management Center Permission". But if I'm not mistaken, it should be just Management permission, no? This is unrelated to Management Center, it's general permission for the management tasks. I think mentioning MC is very confusing here and doesn't bring any value, I suggest omitting it. 

@kwart Could you confirm I understood it correctly?

**Comment by kwart** [comment]
I agree with Jiri.
The messages protected by the ManagementPermissions are part of the client protocol. They are probably only (or mainly) used from the MC, but they are not MC permission.

**Comment by Serdaro** [comment]
Closing with the above commits.
