### ISSUE TITLE
Docs: Feedback for Working with JSON Data in SQL

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hz-docs#414]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/sql/pages/working-with-json.adoc)

There is a inner link to the section [JsonPath](https://docs.hazelcast.com/hazelcast/latest/sql/working-with-json#jsonpath) in the page but there is no such section in the page.

**Comment by Serdaro** [comment]
Thanks a lot @srknzl
