### ISSUE TITLE
Docs: Feedback for Deploy Blue-Green Clusters

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hz-docs#421]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/blue-green.adoc)

Some users assume that once the primary cluster becomes available again, clients would reconnect to that cluster instead of the backup one.  I think we should document that it is not the case (i.e. it does not happen automatically. Needs user config). Considering the number of confusions, we should manage customers' expectation here.

cc: @sancar, @ihsandemir, @mdumandag

**Comment by jgardiner68** [comment]
See https://docs.google.com/document/d/1Zo8JTSnIpYkb0WA8WJ93OoAv4-ON2X3nLiaTyFdON-I/edit#heading=h.90cif122zaev on how to use MC UI and REST interface

**Comment by JakeSCahill** [comment]
I addressed Jame's point in this PR to improve the Management Center docs about client filtering: https://github.com/hazelcast/management-center-docs/pull/206
