### ISSUE TITLE
Docs: Feedback for Ingesting Data from External Sources

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#430]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/ingest/pages/overview.adoc)

The link "MapLoader/MapStore" in https://docs.hazelcast.com/hazelcast/5.1/ingest/overview#available-tools should probably go directly to the MapLoader/Store section in the docs, not to general IMap documentation.

**Comment by Serdaro** [comment]
Also for v/5.1: https://github.com/hazelcast/hz-docs/commit/812c64002e52429fd715ccab27bacd6e56bbd753
