### ISSUE TITLE
Docs: Feedback for Hazelcast Architecture

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hz-docs#441]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/architecture/pages/architecture.adoc)

https://docs.hazelcast.com/hazelcast/5.1/architecture/architecture#hide-nav

The image seems like a draft one. Maybe, I'm wrong :)

**Comment by angelasimms** [comment]
@JakeSCahill @Serdaro, Not sure if this image has already been updated as part of other work? Happy to replace/update if you can point me in the direction of the right details.
