### ISSUE TITLE
How to integrate with Spring Boot correctly

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hz-docs#446]
We should document how to integrate with the latest Spring Boot correctly.

We have issues like hazelcast/hazelcast#21123 caused partially by running 2 different shutdown hooks (Spring's and ours).

There might be a need for some more research, and maybe more tasks will be identified, but we should document what's the best configuration with the current state of things.

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-671](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-671).
