### ISSUE TITLE
Failure at Step 1 of "Get Started with SQL Over Kafka" on M1 Macs

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/hz-docs#476]
on this page: https://docs.hazelcast.com/hazelcast/5.1/sql/learn-sql#hide-nav

this command at step 1 does not run on m1 macs:

`$ docker run --name kafka --network hazelcast-network --rm hazelcast/hazelcast-quickstart-kafka`

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and.  no specific platform was requested docker: Error response from daemon: network hazelcast-network not found.`

**Comment by Serdaro** [comment]
@utkukaratas , Have you tried using the flag `--platform linux/amd64` in the docker command?

**Comment by utkukaratas** [comment]
i suggest using the flag in the docs. 

now that apple silicon is widely used, as a user i assume the docker command would install stuff in my machines architecture. but it seems this project is x86 only, so i'd prefer to see that explicitly mentioned in the docs.

ps. btw kafka has recently uploaded apple silicon images on dockerhub AFAICR so maybe it's better we update the demo app itself.

**Comment by Serdaro** [comment]
Did the command with this extra flag work?

**Comment by utkukaratas** [comment]
hi @Serdaro yes `--platform=linux/amd64` does make it work on m1.

**Comment by amandalindsay** [comment]
Fixed by adding the following tip: 

Tip: If you get an error running this on an M1 Mac, use the flag `--platform=linux/amd64` in the docker command

Will close when PR is merged
