### ISSUE TITLE
Syntax error while running a query from docs:

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hz-docs#483]
Hi,

I'm trying some [SQL stream aggregation](https://docs.hazelcast.com/hazelcast/5.2-snapshot/sql/querying-streams#aggregation) and there appears to be a syntax error in this query:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/158619/179215889-33efa153-dcdc-4ba4-bab4-99e0e2ebfa15.png">

This is what my SQL console says:
```
sql> SELECT window_start, window_end, COUNT(*) AS total_trades
   > FROM TABLE(TUMBLE(
   >   TABLE(trades_ordered),
   >   DESCRIPTOR(trade_time),
   >   INTERVAL '1' MINUTE))
   > GROUP BY 1,2;
Encountered "(" at line 3, column 8.
Was expecting one of:
    <BRACKET_QUOTED_IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BIG_QUERY_BACK_QUOTED_IDENTIFIER> ...
    <HYPHENATED_IDENTIFIER> ...
    <IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
```

~Besides this, I'm not sure whether the tablename `trades_ordered` is correct. Should it be just `trades`? That's the mapping created above:~
<img width="750" alt="image" src="https://user-images.githubusercontent.com/158619/179216104-30512361-c36f-4c7b-81b1-f01d1dc1bc20.png">

Happy Hazelcasting!

**Comment by jerrinot** [comment]
this works:
```
sql> SELECT window_start, window_end, COUNT(*) AS total_trades
   > FROM TABLE(TUMBLE(
   >   TABLE trades_ordered,
   >   DESCRIPTOR(trade_time),
   >   INTERVAL '1' MINUTE))
   > GROUP BY 1,2;
```

**Comment by viliam-durina** [comment]
Yes, it must be `TABLE <space> table_name`, not `TABLE ( table_name )`. `trades_ordered` is a view created later in that page, that's an issue too.
