### ISSUE TITLE
Docs: Feedback for Configuring Maps

### ISSUE THREAD

**Issue by GivaDogaBone** [hazelcast/hz-docs#492]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/map-config.adoc)

To view all possible map settings, refer to the following files included with your Hazelcast distribution.

[hazelcast-full-example.xml](https://github.com/hazelcast/hazelcast/blob/5.1.3/hazelcast/src/main/resources/hazelcast-full-example.xml)

[hazelcast-full-example.yaml](https://github.com/hazelcast/hazelcast/blob/5.1.3/hazelcast/src/main/resources/hazelcast-full-example.xml)

The files above are missing in github.

**Comment by Serdaro** [comment]
Thanks a lot @GivaDogaBone , fixed now.
