### ISSUE TITLE
Docs: Feedback for Store Persistence Data on Intel® Optane™ DC Persistent Memory

### ISSUE THREAD

**Issue by jgardiner68** [hazelcast/hz-docs#499]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/storage/pages/persistence-on-intel.adoc)

Intel has discontinued Optane, so we should decide whether we remove references to it.

See https://www.tomshardware.com/news/intel-kills-optane-memory-business-for-good

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/638/files
