### ISSUE TITLE
Docs: Feedback for License Questions

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hz-docs#52]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-1/docs/modules/ROOT/pages/licenses.adoc)

It mentions Apache 2, but we're dual license now

**Comment by cangencer** [comment]
also I don't think dependency section is relevant, as there's a lot of modules with many other dependencies now.

**Comment by Serdaro** [comment]
@cangencer , I will update the first paragraph to also include the Hazelcast Community License and remove the Embedded and Runtime Dependencies sections.

On second thought, it may be better only to update https://docs.hazelcast.com/hazelcast/latest/#licenses-and-support and remove the License Questions section.

Thoughts?

**Comment by cangencer** [comment]
I think it's fine to merge those two pages, yes

**Comment by Serdaro** [comment]
Fixed with the above commits.
