### ISSUE TITLE
Docs: Feedback for Get Started with Stream Processing (Client/Server)

### ISSUE THREAD

**Issue by mbtmew** [hazelcast/hz-docs#521]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/pipelines/pages/stream-processing-client.adoc)

Should this page indicate JDK 8, 11 & 17 are supported instead of 8-11?

**Comment by Serdaro** [comment]
Updated as 11+, since Hazelcast no more supports JDK 8, starting with 5.3.
