### ISSUE TITLE
Docs: Feedback for Configuring Kubernetes

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#526]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/deploy/pages/configuring-kubernetes.adoc)

These headlines don't really look like headlines. It would be nice if they divided the text somehow.

* https://docs.hazelcast.com/hazelcast/5.1/deploy/configuring-kubernetes#granting-permissions-to-use-kubernetes-api
* https://docs.hazelcast.com/hazelcast/5.1/deploy/configuring-kubernetes#creating-a-service
* https://docs.hazelcast.com/hazelcast/5.1/deploy/configuring-kubernetes#hazelcast-configuration

... and more further down the page.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-docs-ui/releases/tag/v4.1.12

**Comment by Holmistr** [comment]
@Serdaro Aaaaawwwww :) My heart thanks you, Serdar!
