### ISSUE TITLE
Document how to use hazelcast-jet-cdc-mysql in EE

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hz-docs#537]
In this [PR](https://github.com/hazelcast/hazelcast-enterprise/pull/5295) have removed the `hazelcast-jet-cdc-mysql` due to licensing - we are not allowed to distribute it with our EE because it includes MySQL connector under GPL, which would conflict with our EE license.

We should include a note about this somewhere in our documentation, this place seems to be a good candidate:

https://docs.hazelcast.com/hazelcast/5.1/pipelines/cdc#step-4-start-hazelcast

If the user uses EE then they need to download the jar and add it to the lib folder.
The artifact can be downloaded from maven central, for `5.2-BETA-1` the URL would be:

https://repo1.maven.org/maven2/com/hazelcast/jet/hazelcast-jet-cdc-mysql/5.2-BETA-1/hazelcast-jet-cdc-mysql-5.2-BETA-1-jar-with-dependencies.jar

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/9e823eba9757d9d5c452694575936b7d27d50c8e.
Both in BETA and SNAPSHOT documentation.
