### ISSUE TITLE
Docs: Feedback for Updating Map Entries - incomplete java example

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hz-docs#546]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/updating-map-entries.adoc)

Java example is incomplete.
![image](https://user-images.githubusercontent.com/20545793/193601409-a6a70549-b6eb-4f15-a0a8-ff7a3d52bd39.png)

**Comment by Serdaro** [comment]
Thanks a lot @Patras3 ,
Fixed with https://github.com/hazelcast/hz-docs/commit/beffc0a29658f7b0a157b29b12abf7a57f01e180
