### ISSUE TITLE
Sink overview misses the sink names

### ISSUE THREAD

**Issue by vladoschreiner** [hazelcast/hz-docs#55]
In the sink overview, the table actually misses the first column with sink name. The table columns seem to be messed up.

See [here](https://docs.hazelcast.com/hazelcast/5.0-beta-1/pipelines/sources-sinks.html#available-sinks)

The correct state in old Jet docs: [](https://jet-start.sh/docs/api/sources-sinks#sinks)

**Comment by Serdaro** [comment]
Fixed with above commits.
