### ISSUE TITLE
Docs: Feedback for Scaling and Upgrading Hazelcast Clusters in Kubernetes

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/hz-docs#558]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/deploy/pages/scaling-and-upgrading-kubernetes.adoc)

This page needs more meat. 

Getting started page shows you how to start a hz cluster via 3 methods (helm, operator or kubectl). imho we need the same here - "just use the kubectl scale command" doesn't cut it.

**Comment by Serdaro** [comment]
The content section in question has been removed. It will be briefly explained in the operator documentation, as decided by @hasancelik and @cagric0
