### ISSUE TITLE
Docs: Feedback for Start a Local Cluster with the CLI

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hz-docs#566]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/getting-started/pages/get-started-cli.adoc)

The RPM install instructions for both HZ and HZ-MC seem to be incorrect/outdated:

```
wget https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo -O hazelcast-snapshot-rpm.repo
--2022-10-13 08:59:03--  https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo
Resolving repository.hazelcast.com (repository.hazelcast.com)... 2600:9000:2009:7a00:d:c80e:c240:93a1, 2600:9000:2009:b800:d:c80e:c240:93a1, 2600:9000:2009:200:d:c80e:c240:93a1, ...
Connecting to repository.hazelcast.com (repository.hazelcast.com)|2600:9000:2009:7a00:d:c80e:c240:93a1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-13 08:59:03 ERROR 404: Not Found.
```

Based on the contents of https://hazelcast.jfrog.io/ui/native/rpm/snapshot/ it looks like the download URL should be https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm-snapshot.repo

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-675](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-675).
