### ISSUE TITLE
Docs: Document limitations around k8s and Persistence 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hz-docs#579]
Kubernetes scale up/down doesn't work as expected until v5.2.0. 
We need to document the behavior in order to avoid confusions. Please see [this slack discussion](https://hazelcast.slack.com/archives/C0BGM4HSA/p1660063315358109) for more details.

**Comment by Serdaro** [comment]
Below should be considered for 5.0 and 5.1 docs:

* with version prior to 5.2, persistence on kubernetes is risky to operate - see the bullet points in the tech design doc “description” section https://github.com/hazelcast/hazelcast-enterprise/blob/master/docs/design/persistence/04-persistence-kubernetes-improvements.md#description

* you can scale up or down, but cluster-wide shutdown is flawed, can result in OOME and failure to restart the cluster (without requiring manual human operator intervention)

**Comment by amandalindsay** [comment]
Suggest we include the following: 

**Caution**. In versions prior to 5.2.0, persistence on Kubernetes may not work as expected. You can scale up or down, but cluster-wide shutdown can result in OOME and failure to restart the cluster (without requiring manual human operator intervention).

Where should this appear?

- https://docs.hazelcast.com/hazelcast/5.5/kubernetes/kubernetes-persistence#best-practices 

and / or

- https://docs.hazelcast.com/operator/5.14/backup-restore#configuring-persistence

**Comment by amandalindsay** [comment]
PR raised, backported
