### ISSUE TITLE
Docs: Feedback for Apply a Custom Transform with Python

### ISSUE THREAD

**Issue by esandoval30** [hazelcast/hz-docs#583]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/pipelines/pages/python.adoc)

I am getting "Could not find artifact com.hazelcast.jet:hazelcast-jet:pom:5.2.0 in central (https://repo.maven.apache.org/maven2)"

You probably want  this instead?
```xml
<dependency> 
  <groupId>com.hazelcast</groupId>
  <artifactId>hazelcast</artifactId>
  <version>5.2.0</version>
</dependency>
```

**Comment by Serdaro** [comment]
Yes @esandoval30 , the one you wrote is the correct one.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/59f567a0923ab238b725ccd0388edf4cff33c8b7
