### ISSUE TITLE
Docs: Feedback for Member Configuration Files

### ISSUE THREAD

**Issue by ajschutte** [hazelcast/hz-docs#590]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/configuration/pages/configuring-declaratively.adoc)

All the links to the XML and YAML config files are currently broken.

**Comment by Serdaro** [comment]
Thanks a lot for the notice @ajschutte , will fix ASAP.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/f39e430cf1cf270d7432ebfdeda5c431ba0a0619
