### ISSUE TITLE
Document considerations about health check REST endpoints

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hz-docs#595]
In https://docs.hazelcast.com/hazelcast/5.2/maintain-cluster/monitoring#health-check-and-monitoring we should explicitly document that health checks which include the "cluster safe" information can impact heavily loaded clusters. Copying from a [slack thread](https://hazelcast.slack.com/archives/C047ESQN80N/p1667405942257429?thread_ts=1667399913.834999&cid=C047ESQN80N):

> The usefulness of “cluster safety” as a health indicator is questionable in any cluster state other than PASSIVE because the cluster is in a dynamic state. Backups may have fallen temporarily behind (but that’s not unexpected especially for a write-heavy use case). On top of its limited usefulness, check for cluster safety triggers a lot of operations (growing linearly with the number of partitions and replicas).

**Comment by angelasimms** [comment]
Hi @vbekiaris, Just starting to look at this.... Is there any way to disable/exclude the cluster safety check for clusters in an ACTIVE state?
