### ISSUE TITLE
Docs: Feedback for Configuring Maps

### ISSUE THREAD

**Issue by leventathz** [hazelcast/hz-docs#608]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/map-config.adoc)
Links do not work

**Comment by Serdaro** [comment]
Thanks a lot @leventathz , fixed with https://github.com/hazelcast/hz-docs/commit/2ec9680a275d9da1238cc3b9029553fae32bc57c
