### ISSUE TITLE
Docs: Feedback for Updating Map Entries

### ISSUE THREAD

**Issue by jimoconnell** [hazelcast/hz-docs#610]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/updating-map-entries.adoc)

Customer requested a review and possible update to documentation to reflect the behavior and management of metadata.

Metadata grows disproportionately and `map.clear` / `map.delete` operations do NOT clear Metadata.

The only way to shrink Metadata is to destroy the map.

**Comment by sertugkaya** [comment]
related slack discussion: https://hazelcast.slack.com/archives/C034YQBTG/p1669379666478109
