### ISSUE TITLE
Docs: Feedback for Configuring Tiered Storage

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/hz-docs#615]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/tiered-storage/pages/configuration.adoc)

there are other settings under "local-device" entries like "capacity". i had to look this up in the sample config files. i'd prefer this page listed all of those options.

**Comment by Serdaro** [comment]
They are covered in https://docs.hazelcast.com/hazelcast/latest/tiered-storage/configuration#fine-tuning in the same page.

**Comment by utkukaratas** [comment]
nope, i don't see capacity, base-dir, etc... (the full-example config files have them all).

**Comment by Serdaro** [comment]
Thank you, "capacity" has been missed. Will be added.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/629
