### ISSUE TITLE
Docs: Feedback for Configuring Tiered Storage

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/hz-docs#616]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/tiered-storage/pages/configuration.adoc)

> Name of the disk-based (local) device; my-disk in this example

what exactly is a "local" device? who creates it? should i create that beforehand? is this is a lower level linux kernel thing? if so can i use this on a mac/windows? ... i can go on :) just too vague, folks, it needs a lot more explanation.

**Comment by Serdaro** [comment]
... Please see the "note" under https://docs.hazelcast.com/hazelcast/latest/tiered-storage/configuration#configuration-options.

**Comment by amandalindsay** [comment]
Info appears to exist. Closing issue
