### ISSUE TITLE
Docs: Feedback for Data Affinity

### ISSUE THREAD

**Issue by g-donev** [hazelcast/hz-docs#634]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/performance/pages/data-affinity.adoc)

The last paragraph in the section should be brought higher in the section and be better highlighted : "The per map and global (cluster) partitioning strategies are supported on the member side. Hazelcast Java clients only support the global strategy and it is configured via the same system property used in the members (`hazelcast.partitioning.strategy.class `)."

**Comment by Serdaro** [comment]
Closing with the above fixes.
