### ISSUE TITLE
Docs: Feedback for Other Integrations

### ISSUE THREAD

**Issue by g-donev** [hazelcast/hz-docs#655]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/plugins/pages/other-integrations.adoc)

The link to the [Hazelcast Connector for Kafka](https://lenses.stream/connectors/sink/hazelcast.html) is wrong. The URL doesn't exist.

**Comment by Serdaro** [comment]
Thanks a lot @g-donev !
