### ISSUE TITLE
Docs: Feedback for Get Started with SQL Over Maps

### ISSUE THREAD

**Issue by rik-hz** [hazelcast/hz-docs#659]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/sql/pages/get-started-sql.adoc)

The button "Try the Interactive Example" never works. The error suggests it is trying to access katacoda.com, which no longer exists.

We should remove the button, and ideally provide an alternative. But at least remove the button.

**Comment by Serdaro** [comment]
Thank you @rik-hz , we are working on replacing it with killercoda. But yes, let us temporarily remove it.

**Comment by Serdaro** [comment]
Fixed with the above PR, for now.
