### ISSUE TITLE
Docs: Feedback for Release Notes

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hz-docs#66]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-1/docs/modules/ROOT/pages/release-notes.adoc)

We should mention Jet as a new feature - it's only mentioned in the intro part which is easy to miss.

**Comment by Serdaro** [comment]
Fixed: https://docs.hazelcast.com/hazelcast/5.0-beta-2/release-notes.html
