### ISSUE TITLE
Docs: Feedback for Updating Map Entries

### ISSUE THREAD

**Issue by artemiuss** [hazelcast/hz-docs#678]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/updating-map-entries.adoc)

For Python `replace_if_same()` should be used instead of `replace()` in this example:
```
countries.replace( 2, "France", "Spain" )
countries.replace( 3, "United States", "Canada" )
```
->
```
countries.replace_if_same( 2, "France", "Spain" )
countries.replace_if_same( 3, "United States", "Canada" )
````

**Comment by Serdaro** [comment]
Thanks a lot @artemiuss !
