### ISSUE TITLE
Docs: Feedback for Shutting Down the Cluster

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hz-docs#70]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-1/docs/modules/maintain-cluster/pages/shutdown.adoc)

We have some leftover markdown syntax on this page:

`![Cluster Shutdown using Management Center](assets/management-center-shutdown.png)`

**Comment by Serdaro** [comment]
Closing with above fixes.
