### ISSUE TITLE
Docs: Feedback for Member Configuration Files

### ISSUE THREAD

**Issue by EugeneAbramchuk** [hazelcast/hz-docs#700]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/configuration/pages/configuring-declaratively.adoc)

Hazelcast XML samples miss schema declaration and will not work out of the box. I suggest to include it everywhere

```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                  http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.xsd">
```

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-674](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-674)
