### ISSUE TITLE
Docs: Feedback for Deploying Hazelcast Open Source on Kubernetes with Helm

### ISSUE THREAD

**Issue by macmenco** [hazelcast/hz-docs#719]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/kubernetes/pages/helm-hazelcast-chart.adoc)

The documentation to enable the serviceMonitor has a mismatch with the chart, I beleive. 

- metrics.service.serviceMonitor.enabled
- metrics.service.serviceMonitor.namespace 
- metrics.service.serviceMonitor.labels 
- metrics.service.serviceMonitor.interval
- metrics.service.serviceMonitor.scrapeTimeout
- metrics.service.serviceMonitor.relabellings
- metrics.service.serviceMonitor.metricRelabelings
- metrics.service.serviceMonitor.honorLabels

should be 

- metrics.serviceMonitor.enabled
- metrics.serviceMonitor.namespace 
- metrics.serviceMonitor.labels 
- metrics.serviceMonitor.interval
- metrics.serviceMonitor.scrapeTimeout
- metrics.serviceMonitor.relabellings
- metrics.serviceMonitor.metricRelabelings
- metrics.serviceMonitor.honorLabels

According to 
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/servicemonitor.yaml 
and 
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml

**Comment by amandalindsay** [comment]
This appears to have been fixed and there are no instances of 'metrics.service.serviceMonitor' in the page anymore
