### ISSUE TITLE
Docs: Feedback for Deploying User Code on the Member

### ISSUE THREAD

**Issue by jedikcz** [hazelcast/hz-docs#731]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/clusters/pages/deploying-code-on-member.adoc).

The link `generic object interface` in Note section is invalid. I'd say it should point to https://docs.hazelcast.com/hazelcast/5.2/clusters/accessing-domain-objects.

![image](https://github.com/hazelcast/hz-docs/assets/45359017/6d9ddf2f-6605-4e08-83a5-19494fb01e06)

**Comment by Serdaro** [comment]
Fixed with above commits to all 5.x branches.
