### ISSUE TITLE
Docs: Feedback for Configuring Maps

### ISSUE THREAD

**Issue by nishaatr** [hazelcast/hz-docs#740]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/map-config.adoc)

Following links are broken:

![image](https://github.com/hazelcast/hz-docs/assets/12186256/c212c872-c345-4754-924c-447da8aaa7d3)

Thanks
NR

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/839765fef8f9a339a52eb7a061f856626e4de723, also for 5.1 branch.
