### ISSUE TITLE
Docs: Feedback for Locking Maps

### ISSUE THREAD

**Issue by nishaatr** [hazelcast/hz-docs#741]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-structures/pages/locking-maps.adoc)

Should the below read as '...values are **not** equal...' ? Otherwise why replace a value which is equal. May be I am reading this wrong!

![image](https://github.com/hazelcast/hz-docs/assets/12186256/7af0bdb5-ff1c-4ec6-91cc-672d6605f35a)

**Comment by Serdaro** [comment]
Fixed with above commits to all 5.x branches.
