### ISSUE TITLE
Docs: Feedback for CREATE DATA CONNECTION

### ISSUE THREAD

**Issue by jszap** [hazelcast/hz-docs#757]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/sql/pages/create-data-connection.adoc)

the property 'username' for MySQL example is incorrect. It should be 'user' instead.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/813/files
