### ISSUE TITLE
List all options for adding files to members' classpaths

### ISSUE THREAD

**Issue by JakeSCahill** [hazelcast/hz-docs#76]
We have the Adding Java Classes to Members section, which explains code deployment. But we should have an overview that lists all the ways of adding Java class to members such as adding JAR files to the `lib` folder or using the command line.

**Comment by JakeSCahill** [comment]
Dumping some options here in Asciidoc format

[tabs] 
==== 
Gradle:: 
+ 
-- 
[source,groovy,subs="attributes+"]
----
compile 'com.hazelcast.jet:hazelcast-jet-kafka:{page-component-version}'
----
--
Maven:: 
+ 
--
[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>com.hazelcast.jet</groupId>
    <artifactId>hazelcast-jet-kafka</artifactId>
    <version>{page-component-version}</version>
</dependency>
----
--
Other options:: 
+ 
--
. link:https://repo1.maven.org/maven2/com/hazelcast/jet/hazelcast-jet-kafka/5.0-BETA-1/hazelcast-jet-kafka-5.0-BETA-1.jar[Download the JAR file].

. Use one of the following methods to add the JAR file to your members' classpaths:

** Stop members and restart them from the command line, using the `CLASSPATH` environment variable.
+
[source,shell]
----
bin/hz start CLASSPATH=<path_to_jar>
----

** Stop members, and add the JAR file to the `lib` folder of your Hazelcast distribution.

** xref:clusters:deploying-code-from-clients.adoc[Deploy the JAR file to your cluster] without having to restart any members.
--
====

**Comment by Serdaro** [comment]
Closing in favor of https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-665
