### ISSUE TITLE
Docs: Feedback for Partition Group Configuration

### ISSUE THREAD

**Issue by m-u-khayyam** [hazelcast/hz-docs#762]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/clusters/pages/partition-group-configuration.adoc)

The code([HostAwareMemberGroupFactory](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/partition/membergroup/HostAwareMemberGroupFactory.java), [MemberGroupFactoryFactory](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/partition/membergroup/MemberGroupFactoryFactory.java)) ignores the member-group and interfaces configured for partition group HOST_AWARE configuration. And groups the members on the bases of IP addresses.
Document also supports that by saying: "You can group members automatically using the IP addresses of members, so members sharing the same network interface are grouped together. All members on the same host (IP address or domain name) form a single partition group."
But then in the document the configuration xml example is mis leading and shows member group and interfaces being configured for HOST_AWARE as following:

`<hazelcast>
    <partition-group enabled="true" group-type="HOST_AWARE">
        <member-group>
            <interface>10.10.0.*</interface>
            <interface>10.10.3.*</interface>
            <interface>10.10.5.*</interface>
    </partition-group>
</hazelcast>`
 
 
 Whereas it should be only `<partition-group enabled="true" group-type="HOST_AWARE"/> `

Can you please update in all document versions, as it has and is misleading the clients.

**Comment by Serdaro** [comment]
Thanks a lot @m-u-khayyam
