### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hz-docs#77]
Found some links not going to proper places. I would have fixed it myself with a PR but I actually kind find how to reference the other files. Or maybe I'm just lazy to find out on a Friday evening, sorry :) I'll learn from the PRs that you'll send and won't repeat this again, I promise :)

* On https://docs.hazelcast.com/hazelcast/5.0-beta-1/clusters/deploying-code-from-clients.html , the link to generic object interface in the "Note" box is not going anywhere. Probably should go here: https://docs.hazelcast.com/hazelcast/5.0-beta-1/clusters/accessing-domain-objects.html
* On https://docs.hazelcast.com/hazelcast/5.0-beta-1/data-structures/map.html#metadata-policy , the link to HazelcastJsonValue goes to https://docs.hazelcast.com/hazelcast/5.0-beta-1/query/indexing-maps.html#querying-json-strings but that doesn't make sense. Actually the only place where you find info about support of the JSON values is in here in the query section https://docs.hazelcast.com/hazelcast/5.0-beta-1/query/querying-maps-predicates.html#querying-json-strings . I think that while the section should remain there, there should be some other section specific to JSON that we can store JSON values directly. Possibly in the serialization sections?  I know that the only benefit of treating JSON values with HazelcastJsonValue wrapper is querying but still, sounds like a question to be asked frequently.

**Comment by JakeSCahill** [comment]
Thanks @Holmistr. We actually recorded the second bullet here: https://github.com/hazelcast/hz-docs/issues/16 😄

**Comment by Holmistr** [comment]
Ah, nice! :)
