### ISSUE TITLE
Docs: Feedback for List of Hazelcast Metrics - Missing IAtomicReference metric description

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hz-docs#791]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/ROOT/pages/list-of-metrics.adoc)

It looks like IAtomicReference metrics is missing in the "List of Metrics" docs, which is described in this section: 

https://github.com/hazelcast/hazelcast/blob/5.3.z/docs/design/cpsubsystem/03-metrics.md#iatomicreference
"IAtomicReference has no metrics to publish apart from its name. That's why a dummy metric with value equal to 0 will be published. Metric prefix will be cp.atomicref., metric discriminator will be in form of id=name@groupId. There will be name and group tags to show IAtomicReference's name and CP group's name."

**Comment by amandalindsay** [comment]
Topic exists here so I believe we're covered. 
https://docs.hazelcast.com/hazelcast/5.5/data-structures/iatomicreference
