### ISSUE TITLE
Docs: Feedback for Entry Processor

### ISSUE THREAD

**Issue by esandoval30** [hazelcast/hz-docs#807]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/computing/pages/entry-processor.adoc)

In the note: "The entry processor is meant to process a single entry per call. Processing multiple entries and data structures in an entry processor is not supported as it may result in deadlocks. To process multiple entries, use a [data pipeline](https://docs.hazelcast.com/hazelcast/5.3/pipelines/overview) with the [entry processor sink](https://docs.hazelcast.com/hazelcast/5.3/integrate/connectors)."

The link to "entry processor sink" takes the user to the connectors..However, there is no entry processor sink listed there

**Comment by amandalindsay** [comment]
Topic not found, closing issue
