### ISSUE TITLE
Docs: Feedback for Configuring Data Connections to External Systems

### ISSUE THREAD

**Issue by jgardiner68** [hazelcast/hz-docs#815]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/data-connections/pages/data-connections-configuration.adoc)

Can we remove the BETA tag (in the heading)?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/820
