### ISSUE TITLE
Docs: Feedback for 5.3.0 Release Notes

### ISSUE THREAD

**Issue by myawnhc** [hazelcast/hz-docs#816]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/release-notes/pages/5-3-0.adoc)

The statement about no longer supporting JDK 8 provides no useful guidance to the reader - should be stated in terms of what is supported instead (minimum of JDK 11, for example, if that's the current requirement).

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/577aa68acccbc02ea14ba1151ba15721aced3f5e
