### ISSUE TITLE
Docs: Feedback for Split-Brain Protection

### ISSUE THREAD

**Issue by m-u-khayyam** [hazelcast/hz-docs#850]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/network-partitioning/pages/split-brain-protection.adoc)

The documentation mentions that "If the cluster size is below this minimum value, the operations are rejected and the rejected operations return a SplitBrainProtectionException to their callers",  but please note that a SplitBrainProtectionException is not thrown a/few the data structures. e.g. ExecutorService etc. 

it should be clarified in the document as for now it conveys like the ExecutorService also throws exception. It can furtehr suggest that submit instead of execute can be used if client cares to be notified of exception.

Future<Void> future = newHazelcastClient(config).getExecutorService("esWithSplitBrainProtection").submit(() -> {
    doSomething();
    return null;
});
// inspect the outcome
future.get(); // this will throw ExecutionException wrapping SplitBrainProtectionException

**Comment by Serdaro** [comment]
Closing in favor of [DOCS-677](https://hazelcast.atlassian.net/jira/software/projects/DOCS/boards/60/timeline?selectedIssue=DOCS-677).
