### ISSUE TITLE
`Check for dead links` action failing

### ISSUE THREAD

**Issue by JackPGreen** [hazelcast/hz-docs#852]
The [`Check for dead links` action](https://github.com/hazelcast/hz-docs/actions/workflows/validate.yml) has been failing for a while:

- [first failure](https://github.com/hazelcast/hz-docs/actions/runs/5517030005/job/14936194493) - July 11, 2023 08:24
- [last success](https://github.com/hazelcast/hz-docs/actions/runs/5458415680/job/14777434551) - July 4, 2023 22:09

```
ERROR (asciidoctor): target of xref not found: tutorials:ROOT:sql-on-viridian.adoc
    file: docs/modules/ROOT/pages/create-postgres-connection.adoc
    source: https://github.com/hazelcast/cloud-docs (branch: main | start path: docs)
ERROR (asciidoctor): target of xref not found: imdg:management:metrics.adoc
    file: docs/modules/ROOT/pages/management-center-persistence.adoc
    source: https://github.com/hazelcast/hazelcast-platform-operator-docs (branch: main | start path: docs)
```

**Comment by JackPGreen** [comment]
The `create-postgres-connection` file was added in https://github.com/hazelcast/cloud-docs/pull/122 - that looks to be the first reference to `sql-on-viridian` that I can see. But I can't see any reciprocal PR or branch in the `hz-docs` repo.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/pull/872
