### ISSUE TITLE
Docs: Feedback for Predicates API

### ISSUE THREAD

**Issue by CREFaulk** [hazelcast/hz-docs#878]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/query/pages/predicate-overview.adoc)

The below doesn't seem to be valid past a certain release. EntryObject isn't defined and newPredicateBuilder is not defined in Predicates anymore.

```
IMap<String, Employee> map = hazelcastInstance.getMap( "employee" );

EntryObject e = Predicates.newPredicateBuilder().getEntryObject();
Predicate predicate = e.is( "active" ).and( e.get( "age" ).lessThan( 30 ) );

Collection<Employee> employees = map.values( predicate );
```

I something like this might be more current? (Just guessing, since I can't actually run it)
```
IHMap<String, Employee> map = hazelcastInstance.getMap( "employee" );

var criteriaQuery = Predicates.And(
    Predicates.EqualTo("active", true),
    Predicates.LessThan("age", 30)
);

Collection<Employee> employees = await map.GetValueAsync( criteriaQuery);
```

**Comment by Serdaro** [comment]
@CREFaulk , the content is correct (for Java members and clients).
I think you are mentioning .NET client; if so, please see https://hazelcast.github.io/hazelcast-csharp-client/latest/doc/distributedQuery.html.

**Comment by CREFaulk** [comment]
Ah ok, thanks. I was actually looking at this page originally:
https://docs.hazelcast.com/hazelcast/5.3/query/predicate-overview

I was having a really difficult time finding documentation at Hazelcast.net (and Google) but eventually did find the .net project on github after seeing the documentation link.

**Comment by Serdaro** [comment]
This is a great feedback about findability of the .NET client documentation, thanks a lot. Added to our backlog.
Closing this issue for now.
