### ISSUE TITLE
Docs: Feedback for Using the Data Migration Tool

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hz-docs#902]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/migrate/pages/data-migration-tool.adoc)

The link to get the data migration tool just points to Viridian and to hazelcast.com. It is not readily apparent where to find the tool in either place. Is it actually available, and if so, please update the links in the docs accordingly.

Heck, I can't even find it on GitHub, but that's a different story...

**Comment by pmcgleenon** [comment]
Noticed this too.  I don't believe there's a link available on Viridian to download the DMT

**Comment by amandalindsay** [comment]
So the DMT never did GTM so it is not on the website, and the topic is not visible. Closing ticket
