### ISSUE TITLE
hazelcast.client.invocation.timeout.seconds can be improved

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hz-docs#94]
Regarding `hazelcast.client.invocation.timeout.seconds` property

As stated in https://docs.hazelcast.com/imdg/4.2/clients/java.html#handling-failures part,

invocation timeout is important for the 3 following cases:

* Member throws an exception.

* Connection between the client and member is closed.

* Client’s heartbeat requests are timed out.

in the properties table only one of them stated. We should add other ones too.

**Comment by Serdaro** [comment]
Fixed with above commits.
