### ISSUE TITLE
Docs: Feedback for 5.3.6 Release Notes

### ISSUE THREAD

**Issue by padmajan87** [hazelcast/hz-docs#944]
Hi Team,
   hz-cli script in 5.3.6 version complains that the client version is 5.2.3 and it is not compatible with server version 5.3.6.
Could you please suggest what might be the issue.

Regards,
Padmajan V

**Comment by Serdaro** [comment]
See https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1703755969922349
