### ISSUE TITLE
Docs: Feedback for Configuring for IMap and ICache

### ISSUE THREAD

**Issue by erkangurgen** [hazelcast/hz-docs#983]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/wan/pages/configuring-for-map-and-cache.adoc)

The merge policy property "merge-policy" is replaced with  "merge-policy-class-name" , starting from version 4.0.

the config snippet should be as follows,
 
```
<map name="my-shared-map">
        <wan-replication-ref name="london-wan-rep">
            <merge-policy-class-name>PassThroughMergePolicy</merge-policy-class-name>
            <republishing-enabled>false</republishing-enabled>
        </wan-replication-ref>
    </map>
    ```

**Comment by amandalindsay** [comment]
Checked file and this issue has already been fixed

**Comment by amandalindsay** [comment]
Closing as fixed
