### ISSUE TITLE
Docs: Feedback for About Stream Processing Pipelines

### ISSUE THREAD

**Issue by Petkomat** [hazelcast/hz-docs#988]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/pipelines/pages/building-pipelines.adoc)

The source

```
we are no longer waiting for events with timestamp `t_b <= t_a - maxLag`
```

is rendered as _we are no longer waiting for events with timestamp `t_b ⇐ t_a - maxLag`_, i.e., the inequality is wrongly rendered as an "Leftarrow". Maybe, it is worth checking the other pages as well.

**Comment by Serdaro** [comment]
Thank you @Petkomat
