### ISSUE TITLE
Docs: Feedback for Upgrading to Hazelcast 5.0

### ISSUE THREAD

**Issue by Marki4711** [hazelcast/hz-docs#99]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/v/5.0-beta-2/docs/modules/migrate/pages/upgrade.adoc)

The Java client is not mentioned. Is the compatibility of the Java client identical to .NET, C++. Python and Node.js?

BR,
Matthias

**Comment by Serdaro** [comment]
Hello @Marki4711 , Java client is a native client of Hazelcast. Since Hazelcast 5.0 is fully compatible with former Hazelcast IMDG 4.x and 3.12.x versions, so is the Java client.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hz-docs/commit/7989b7ed9e2eec56edabadde37d394bc9505c621
